### ISSUE TITLE
Pool?

### ISSUE THREAD

**Issue by yovanoc** [sinclairzx81/threadbox#2]
A pool implementation is planned? Thanks

**Comment by sinclairzx81** [comment]
@yovanoc Hi,

I've actually left thread pooling out of this library as it's fairly straight forward for users to implement their own. It's hard to capture all the features users would want to do with respect to thread pooling under a single `ThreadPool` type, so i figured it's better to leave this implementation to the user.

That said, the following implements a very basic thread pool where the actual scheduling is done via simple random `threadIdx` selection. Actual implementations may want to opt for round-robin or buffered async queue or other application specific functionality.

```typescript
import { Thread, Main, spawn } from '@sinclair/threadbox'

@Thread() export class Example {
    constructor(private readonly threadIdx: number) {}

    public add(a: number, b: number) {
        console.log(`threadIdx ${this.threadIdx}: ${a} + ${b} = ${a + b}`)
        return a + b
    }
}

@Main() default class {
    public async main() {
        // thread pool of 4 threads.
        const pool = [
            spawn(Example, 0),
            spawn(Example, 1),
            spawn(Example, 2),
            spawn(Example, 3)
        ]

        // execute 'add(...)' on random thread.
        for(let i = 0; i < 1000; i++) {
            const threadIdx = (Math.random() * pool.length) | 0
            const thread    = pool[threadIdx]
            const result    = await thread.add(i, i + 1)
        }

        // dispose of the pool.
        for(const thread of pool) {
            thread.dispose()
        }
    }
}
```
Hope this helps! Open to suggestions if you had something else in mind with regards to pooling threads.
S

**Comment by sinclairzx81** [comment]
Will close off this issue but thanks for the suggestion. I dont anticipate a specific thread pool implementation under the current API, but would be open to making user implementations easier. I expect this will probably be in the form of additional TypeScript constraint and interface types more than changes to the runtime / api. 

Thanks Again
S
